-- Tabela para Cache Parcial Inteligente (Fase 2)
CREATE TABLE IF NOT EXISTS partial_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_hash VARCHAR(64) UNIQUE NOT NULL,
    component_type VARCHAR(20) NOT NULL, -- 'diagnosis', 'library', 'tactical'
    result_json JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    hit_count INTEGER DEFAULT 1,
    last_used TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_partial_cache_hash ON partial_cache(component_hash);
CREATE INDEX IF NOT EXISTS idx_partial_cache_type ON partial_cache(component_type);
CREATE INDEX IF NOT EXISTS idx_partial_cache_created ON partial_cache(created_at);
CREATE INDEX IF NOT EXISTS idx_partial_cache_last_used ON partial_cache(last_used);

-- Limpeza automática de entradas antigas (opcional)
-- CREATE OR REPLACE FUNCTION cleanup_old_partial_cache()
-- RETURNS void AS $$
-- BEGIN
--     DELETE FROM partial_cache WHERE created_at < NOW() - INTERVAL '7 days';
-- END;
-- $$ LANGUAGE plpgsql;
