-- Tabelas necessárias para o fluxo de créditos e assinaturas (compatível com Streamlit e FastAPI)
-- Execute no Supabase SQL Editor (Database > SQL Editor)

-- 1) user_credits: créditos avulsos (one-time)
CREATE TABLE IF NOT EXISTS public.user_credits (
    user_id TEXT PRIMARY KEY,
    balance INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2) subscriptions: assinaturas recorrentes (premium_plus)
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    subscription_plan TEXT NOT NULL, -- ex: 'premium_plus'
    subscription_status TEXT NOT NULL, -- ex: 'active', 'canceled', 'incomplete'
    current_period_start TIMESTAMPTZ NOT NULL,
    current_period_end TIMESTAMPTZ NOT NULL,
    stripe_subscription_id TEXT,
    stripe_customer_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, subscription_plan) -- apenas uma assinatura por plano por usuário (simplificado)
);

-- 3) usage: controle de uso mensal para assinaturas (premium_plus)
CREATE TABLE IF NOT EXISTS public.usage (
    user_id TEXT NOT NULL,
    period_start TIMESTAMPTZ NOT NULL, -- início do período mensal (ex: primeiro dia do mês)
    used INTEGER NOT NULL DEFAULT 0,
    usage_limit INTEGER NOT NULL DEFAULT 30, -- limite mensal para premium_plus
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, period_start)
);

-- Opcional: índices para performance
CREATE INDEX IF NOT EXISTS idx_user_credits_user_id ON public.user_credits(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON public.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON public.subscriptions(subscription_status);
CREATE INDEX IF NOT EXISTS idx_usage_user_id_period ON public.usage(user_id, period_start);

-- 4) free_usage: controle de uso da análise gratuita (1 por usuário)
CREATE TABLE IF NOT EXISTS public.free_usage (
    user_id TEXT PRIMARY KEY,
    used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índice para performance
CREATE INDEX IF NOT EXISTS idx_free_usage_user_id ON public.free_usage(user_id);

-- Opcional: RLS (Row Level Security) se quiser restringir acesso via client-side
-- Para MVP, pode deixar desabilitado (RLS off) e controlar tudo via service_role no backend.
